 - hosts : node-http
   tasks: 
   - name: create files 
     copy:
       dest: /home/ec2-user/index.html
       content: <h1> Made from TerraForm and Ansible</h1> 
   - name: create server
     shell: "nohup busybox httpd -f -p 8080 & "